### ISSUE TITLE
Can't use custom ONNX file

### ISSUE THREAD

**Issue by assi98** [doughtmw/HoloLens2-Machine-Learning#17]
I have tried to use several ONNX files to run in this example, but i am not able to. I am only able to run it with the one that is given i the repo. Any suggestions on what I could do to upload and use my own?

**Comment by doughtmw** [comment]
Hi @assi98, please take a look at [another repository of mine](https://github.com/doughtmw/surgeon-assist-net) for more details on preparing the ONNX models. It's unfortunately not quite plug-n-play to get these models to work with WinML, and there is typically some additional modifications that are required.
