### ISSUE TITLE
Parameter is incorrect when using own trained model

### ISSUE THREAD

**Issue by syedali1621** [doughtmw/HoloLens2-Machine-Learning#2]
We trained our own model with one class using tensorflow 2.2 with keras and converted the model to .onnx by following your instructions. our model is trained with 1 class when we use this new model, in the hololens, this message appears " Error init. The Parameter is incorrect".
 Could you let me know which parameter is incorrect ?

Thank you

**Comment by doughtmw** [comment]
Hi @syedali1621, the conversion process from TensorFlow or PyTorch to ONNX can be especially challenging as only certain versions of ONNX models are compatible with the HoloLens 2 and WindowsML inference. There are more details of this conversion process beginning with a PyTorch trained model in another repo of mine [[link]](https://github.com/doughtmw/surgeon-assist-net).
