### ISSUE TITLE
unity main camera scripts

### ISSUE THREAD

**Issue by zeinabh94** [doughtmw/HoloLens2-Machine-Learning#5]
Hello,

 I’m interested about HoloLens2 and I want to try this project in Unity but main camera doesn’t have any scripts . 
Can you guide me on this ?! 
Which scripts I have to use?!

 Thank you !

**Comment by doughtmw** [comment]
Hi @zeinabh94, those scripts on the main camera are not required for running the sample and have been removed in the most recent commit. The relevant script is attached to the `ScriptHolder` game object in the main Unity scene.
