### ISSUE TITLE
Run on GPU

### ISSUE THREAD

**Issue by lihzh233** [doughtmw/HoloLens2-Machine-Learning#6]
Hi, I want to run the model on GPU. I notice some annotating code about GPU in model.cs. I try to use that code, but it doesn't work. Would you help me with that? Thank you!

**Comment by doughtmw** [comment]
Hi @lihzh233, unfortunately GPU inference support with ONNX models on the HoloLens 2 is really not that performant or well supported. 

In my own testing I've found that using CPU software bitmaps and CPU inference is significantly faster than copying your bitmaps to the GPU and performing inference there. There are some more performance details as to how to optimize ONNX inference speeds on the HoloLens 2 CPU in [another repo of mine](https://github.com/doughtmw/surgeon-assist-net#:~:text=Deploy%20and%20run%20the%20sample%20on%20the%20HoloLens%202).
